In [45]:
import numpy as np


In [46]:
a=np.array([1,2,3,4], dtype='float64')
a.shape
a.dtype



dtype('float64')

In [47]:

print(a[1:])

[2. 3. 4.]


In [48]:
b = np.array([[1,2,4,3,4], 
[1,2,3,4,5],[1,2,3,4,4],[1,2,3,4,4],[1,2,3,4,4],[1,2,3,4,4],[1,2,3,4,4],[7,3,4,3,4]])



In [49]:
b.shape

(8, 5)

In [50]:
print(b[4,4]+20)
print(b[4,4])

24
4


In [51]:
a = np.arange(5)
print(a+20)
print(a)

[20 21 22 23 24]
[0 1 2 3 4]


In [52]:
print(b[4,:3])

[1 2 3]


In [53]:
# print(b[])

In [54]:
b.ndim

2

In [55]:
c= np.array([[[[1,2,3,4,4], [2,3,4,5,6],[1,2,3,4,4],[1,2,3,4,4],[1,2,3,4,4],[1,2,3,4,4]]]])
print(c[2:,:1])

[]


In [56]:
c.ndim

4