In [ ]:
#   starting with numpy...
#   you generally need to start with np.array{[]) and then putting yout list in [1,2,,4] bracket's


In [37]:
import numpy as np


In [38]:
a= np.array([1,2,4,5,5],dtype=np.float64)
#  changing int to float...

In [39]:
a[0]

1.0

In [40]:
a[0:]

array([1., 2., 4., 5., 5.])

In [41]:
a[0:5]

array([1., 2., 4., 5., 5.])

In [42]:
a.dtype
# printing intput data type...

dtype('float64')

In [43]:
b = np.array([1,2,3,4.4])
b.dtype

dtype('float64')

In [44]:
g= np.array([[[1,2,3,3], [1,2,3,5], [1,2,4,5], [1,3,4,6]]])
g= np.array([[[1,2,3,3], [1,2,3,5], [1,2,4,5], [1,3,4,6]]])

In [45]:
g.shape


(1, 4, 4)

In [46]:
g.ndim


3

In [47]:
g.size

16

In [48]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])


#  printing slicing

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [49]:
print(A[1:, :2])

# here it means take one also and more futher, but when you place before decimal will take all number before the decimal.

[['d' 'e']
 ['g' 'h']]


In [50]:
a = np.arange(5)
a + 20
# print(a+20)
print(a)

[0 1 2 3 4]


In [51]:
#  Starting with Boolean operator,,,

# ** 
# There are three types of for selecitn in a array.
# first iwht brack wihc is normal ,
# second is with [[]] double bracket.
# Third with boolean array..

#  **#

In [52]:
a[[True, False, True, False, True]]

array([0, 2, 4])

In [53]:
a>=2

array([False, False,  True,  True,  True])

In [54]:
a[a>=2] 
#   saying that hey from  go to al list which are the numbers. less than or equal to 2 from the a print them

#  this is also know as filteration of arrays

array([2, 3, 4])

In [55]:
a[a> a.mean()]

array([3, 4])

In [56]:
a[(a == 1) & (a==3)]

array([], dtype=int32)

In [65]:
a[(a==0)| (a==1)]
# print(a[(a==2) & (a==4)])

array([0, 1])

In [75]:
a[(a<=2) &(a%2==0)]

array([0, 2])

In [80]:
a[(a<=2) &(a%2==0)]

array([0, 2])